<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/**
 * @file
 * Helper module for apigee_edge tests.
 */

use Drupal\apigee_mock_api_client\Plugin\KeyProvider\TestEnvironmentVariablesKeyProvider;

/**
 * Implements hook_key_provider_info_alter().
 */
function apigee_m10n_test_key_provider_info_alter(array &$key_providers) {
  // This key provider override will make sure credentials are available during
  // functional test callbacks.
  $key_providers['apigee_edge_environment_variables']['class'] = TestEnvironmentVariablesKeyProvider::class;
}
