<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/**
 * @file
 * Helper module for the apigee_edge tests.
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\user\UserInterface;

/**
 * Implements hook_apigee_edge_my_developer_apps_title_alter().
 *
 * Tests "My developer apps" title alter hook.
 *
 * @see \Drupal\Tests\apigee_edge\Functional\DeveloperAppUITest
 */
function apigee_edge_test_apigee_edge_my_developer_apps_title_alter(TranslatableMarkup &$title, ?UserInterface $user = NULL) {
  $title = new TranslatableMarkup('Foo @original', [
    '@original' => $title,
  ]);
}
