<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/**
 * Implements hook_install().
 */
function apigee_edge_test_install() {
  \Drupal::configFactory()->getEditable('apigee_edge_debug.settings')
    ->set('log_message_format', "
<pre>{request_formatted}</pre>

<pre>{response_formatted}</pre>

<p>Transfer statistics: <pre>{stats}</pre></p>")
    ->set('formatter', 'full_html')
    ->save();

  // Increase timeout of the API client to ensure tests do not fail.
  \Drupal::configFactory()->getEditable('apigee_edge.client')
    ->set('http_client_timeout', 120)
    ->save();
}
