<?php

/**
 * @file
 * Helper module for the Apigee Edge Team module tests.
 */

use Drupal\apigee_edge_teams\Entity\TeamInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_apigee_edge_teams_developer_permissions_by_team_alter().
 *
 * Grant all test permissions to a member of team independently from its current
 * team roles within the team.
 */
function apigee_edge_teams_test_apigee_edge_teams_developer_permissions_by_team_alter(array &$permissions, TeamInterface $team, AccountInterface $account) {
  if ($account->isAnonymous()) {
    // Anonymous user can not be member of a team.
    return;
  }
  /** @var \Drupal\apigee_edge_teams\TeamMembershipManagerInterface $team_membership_manager */
  $team_membership_manager = \Drupal::service('apigee_edge_teams.team_membership_manager');
  /** @var \Drupal\apigee_edge_teams\TeamPermissionHandlerInterface $team_permission_handler */
  $team_permission_handler = \Drupal::service('apigee_edge_teams.team_permissions');
  try {
    $developer_teams = $team_membership_manager->getTeams($account->getEmail());
  }
  catch (Exception $e) {
    $developer_teams = [];
  }

  if (in_array($team->id(), $developer_teams)) {
    foreach ($team_permission_handler->getPermissions() as $permission) {
      if (strpos($permission->getName(), 'test') === 0) {
        $permissions[] = $permission->getName();
      }
    }
  }
}
